config/routes.rb
Rails.application.routes.draw do
  resources :vitimas, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :doadores, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :conexoes, only: [:new, :create, :index, :edit, :update, :destroy]
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conexao.rb
class Conexao < ApplicationRecord
  belongs_to :vitima
  belongs_to :doador
end

app/models/doador.rb
class Doador < ApplicationRecord
  has_many :conexoes
  has_many :vitimas, through: :conexoes
end

app/models/vitima.rb
class Vitima < ApplicationRecord
  has_many :conexoes
  has_many :doadores, through: :conexoes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doadores_controller.rb
class DoadoresController < ApplicationController
  def index
    @doadores = Doador.all
  end

  def new
    @doador = Doador.new
  end

  def create
    @doador = Doador.new(doador_params)
    if @doador.save
      redirect_to doadores_path, notice: 'Doador cadastrado com sucesso.'
    else
      render :new
    end
  end

  def edit
    @doador = Doador.find(params[:id])
  end

  def update
    @doador = Doador.find(params[:id])
    if @doador.update(doador_params)
      redirect_to doadores_path, notice: 'Doador atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @doador = Doador.find(params[:id])
    @doador.destroy
    redirect_to doadores_path, notice: 'Doador removido com sucesso.'
  end

  private

  def doador_params
    params.require(:doador).permit(:nome, :telefone, :endereco, :ofertas)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/vitimas_controller.rb
# app/controllers/vitimas_controller.rb
class VitimasController < ApplicationController
  def index
    @vitimas = Vitima.all
  end

  def new
    @vitima = Vitima.new
  end

  def create
    @vitima = Vitima.new(vitima_params)
    if @vitima.save
      redirect_to vitimas_path, notice: 'Vítima cadastrada com sucesso.'
    else
      render :new
    end
  end

  def edit
    @vitima = Vitima.find(params[:id])
  end

  def update
    @vitima = Vitima.find(params[:id])
    if @vitima.update(vitima_params)
      redirect_to vitimas_path, notice: 'Vítima atualizada com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @vitima = Vitima.find(params[:id])
    @vitima.destroy
    redirect_to vitimas_path, notice: 'Vítima removida com sucesso.'
  end

  private

  def vitima_params
    params.require(:vitima).permit(:nome, :telefone, :endereco, :necessidade)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doadores_helper.rb
module DoadoresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vitimas_helper.rb
module VitimasHelper
end

app/views/doadores/create.html.erb
<h1>Doadores#create</h1>
<p>Find me in app/views/doadores/create.html.erb</p>

app/views/doadores/edit.html.erb
<h1>Cadastrar Doador</h1>
<%= form_with model: @doador, local: true do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>
  <div>
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>
  <div>
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>
  <div>
    <%= form.label :ofertas %>
    <%= form.text_field :ofertas %>
  </div>
  <div>
    <%= form.submit 'Cadastrar' %>
  </div>
<% end %>

app/views/doadores/index.html.erb
<h1>Lista de Doadores</h1>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Endereço</th>
      <th>Ofertas</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @doadores.each do |doador| %>
      <tr>
        <td><%= doador.nome %></td>
        <td><%= doador.telefone %></td>
        <td><%= doador.endereco %></td>
        <td><%= doador.ofertas %></td>
        <td>
          <%= link_to 'Excluir', doador_path(doador, token: doador.token), method: :delete, data: { confirm: 'Tem certeza?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/doadores/new.html.erb
<h1><%= action_name == 'new' ? 'Adicionar Doador' : 'Editar Doador' %></h1>

<%= form_with model: @doador, local: true do |form| %>
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <

app/views/doadores/update.html.erb
<h1>Doadores#update</h1>
<p>Find me in app/views/doadores/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bem-vindo ao Cadastro de Vítimas e Doadores</h1>
<%= link_to 'Cadastrar Vítima', new_vitima_path %>
<%= link_to 'Cadastrar Doador', new_doador_path %>
<%= link_to 'Lista de Vítimas', vitimas_path %>
<%= link_to 'Lista de Doadores', doadores_path %>

app/views/vitimas/create.html.erb
<h1>Vitimas#create</h1>
<p>Find me in app/views/vitimas/create.html.erb</p>

app/views/vitimas/destroy.html.erb
<h1>Vitimas#destroy</h1>
<p>Find me in app/views/vitimas/destroy.html.erb</p>

app/views/vitimas/edit.html.erb
<h1><%= action_name == 'new' ? 'Adicionar Vítima' : 'Editar Vítima' %></h1>

<%= form_with model: @vitima, local: true do |form| %>
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :necessidade %>
    <%= form.text_area :necessidade %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/vitimas/index.html.erb
<!-- app/views/vitimas/index.html.erb -->
<h1>Vítimas</h1>
<%= link_to 'Adicionar Vítima', new_vitima_path, class: 'btn btn-primary' %>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Endereço</th>
      <th>Necessidade</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @vitimas.each do |vitima| %>
      <tr>
        <td><%= vitima.nome %></td>
        <td><%= vitima.telefone %></td>
        <td><%= vitima.endereco %></td>
        <td><%= vitima.necessidade %></td>
        <td>
          <%= link_to 'Editar', edit_vitima_path(vitima), class: 'btn btn-secondary' %>
          <%= link_to 'Excluir', vitima_path(vitima), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vitimas/new.html.erb
<h1><%= action_name == 'new' ? 'Adicionar Vítima' : 'Editar Vítima' %></h1>

<%= form_with model: @vitima, local: true do |form| %>
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :necessidade %>
    <%= form.text_area :necessidade %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/vitimas/update.html.erb
<h1>Vitimas#update</h1>
<p>Find me in app/views/vitimas/update.html.erb</p>